site_name: SpaceWorld
repo_url: https://github.com/Binobinos/SpaceWorld-SLI

theme:
  name: furo
  features:
    - navigation.tracking
    - content.tabs.link

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences