name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Run tests with pytest
        run: pytest -v --cov
        env:
          PYTHONPATH: "${{ github.workspace }}"

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage-reports

      - name: Combine coverage
        run: |
          pip install coverage
          python -m coverage combine coverage-reports/coverage-*
          python -m coverage report
          python -m coverage xml

      - name: Upload combined coverage
        uses: codecov/codecov-action@v3